### ISSUE TITLE
Sometimes a character cannot jump

### ISSUE THREAD

**Issue by mifth** [AdilDevStuff/2D-Platformer-Starter-Kit#3]
I've found a strange issue. If I hold "D" key and jump then a character do3esn't jump too high. 

I recorded a video:
[2024-02-01 15-16-07.zip](https://github.com/AdilDevStuff/2D-Platformer-Starter-Kit/files/14126580/2024-02-01.15-16-07.zip)

**Comment by AdilDevStuff** [comment]
It was happening mainly due to the character's collision being stuck in the platform, so i partially fixed it by making the platform a one way platform so it goes through the platforms without stucking! Thanks for letting me know!
